server:
  port: 669
  context-path: /

spring:
  application:
    name: togo
  jackson:
    serialization:
      indent-output: true
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
      
logging:
  level:
    root: info
  path: /data/logs/togo/

    
